/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc4g550.vista;

import com.mycompany.parchisc4g550.controlador.ControladorPrincipal;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class GUIJugador extends javax.swing.JFrame {

    /**
     * Creates new form GUIJugador
     */
    public GUIJugador(ControladorPrincipal controlador) {
        initComponents();
        btnContinuar.addActionListener(controlador);
    }

    public String getCbColor() {
        return (String) cbColor.getSelectedItem();
    }

    public String getTxtJugador1() {
        return txtJugador1.getText();
    }

    public String getTxtJugador2() {
        return txtJugador2.getText();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJugador1 = new javax.swing.JTextField();
        txtJugador2 = new javax.swing.JTextField();
        cbColor = new javax.swing.JComboBox<>();
        btnContinuar = new javax.swing.JButton();
        jlFondoPersonaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtJugador1.setColumns(20);
        getContentPane().add(txtJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 220, 40));

        txtJugador2.setColumns(20);
        getContentPane().add(txtJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, 40));

        cbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------", "Amarillo", "Rojo", "Azul", "Verde" }));
        getContentPane().add(cbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 30));

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonContinuar.png"))); // NOI18N
        btnContinuar.setActionCommand("Continuar");
        btnContinuar.setBorderPainted(false);
        btnContinuar.setContentAreaFilled(false);
        getContentPane().add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, -1, -1));

        jlFondoPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoPersonaje.png"))); // NOI18N
        getContentPane().add(jlFondoPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> cbColor;
    private javax.swing.JLabel jlFondoPersonaje;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}
